/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.viewport;

import controller.Intent;
import controller.IntentMap.IntentMap;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.GameObject;
import model.entity.occupation.ability.Ability;
import model.entity.occupation.ability.instantAbility.itemAbility.SetTrap;
import model.entity.occupation.ability.instantAbility.projectile.Firebolt;

/**
 *
 * @author darien
 */
public class AbilitiesViewport extends ViewPort {
    
    /*Properties*/
    
    private ArrayList<IntentMap> ims = new ArrayList<IntentMap>(1);
    //
    private int mostRecentNumAbilities = -1; //nonsense value to ensure first update
    
    /*Constructors*/
    
    public AbilitiesViewport() {
        initComponents();
    }
    
    /*Methods*/
    
    // -----------------------------------------------------
   @Override
    public void updateView(GameObject gameObject) {      
        
        ArrayList<Ability> abilities = gameObject.getAvatar().getAbilities();
        
        if (refreshNeeded(abilities)) {
            loadAbilities(abilities);
        }
      
    }
    
    @Override
    public ArrayList<IntentMap> generateIntentMapping() {
        return ims;
    } 
    
    private boolean refreshNeeded(ArrayList<Ability> abilities) {
        int numAbilities = abilities.size();
        if (numAbilities != mostRecentNumAbilities) {
            refreshControllerNeeded = true;
        } else {
            refreshControllerNeeded = false;
        }
        return refreshControllerNeeded;
    }
    
    // -----------------------------------------------------
    private void loadAbilities(ArrayList<Ability> abilities){
        if (abilities.size() < 3) {
            abilities.add(new Firebolt());
            abilities.add(new SetTrap());
        }

        Ability ability = null;
        Component component = null;
        Component[] components = this.getComponents();
        
        //while there are still abilities (and space to display them
        for (int i=0; i<components.length && i<abilities.size(); i++ ){
            component = components[i];
            ability = abilities.get(i);
            
            if ( component instanceof JPanel ){
                
                JPanel panel = (JPanel)component;

                loadAbilitiesIntoPanel(ability, panel);
            }
            
        }
       
    }
   
    private void loadAbilitiesIntoPanel(Ability ability, JPanel panel) {
        Component[] components = panel.getComponents();
        Component component = null;
        
        for (int i=0; i<components.length; i++) {

            component = components[i];
            
            if ( component instanceof JButton){

                JButton button = (JButton)component;
                //setup button visual
                ImageIcon image = new ImageIcon( ability.getIcon().getImage() );
                button.setIcon(image);
                button.repaint();   
                //setup button action
                ims.add(new IntentMap(button, ability, Intent.ACTIVATE_ABILITY));
            }
            else if ( component instanceof JLabel){

                JLabel nameLabel = (JLabel)component;
                nameLabel.setText(ability.getName() );

                nameLabel.repaint();

            }
            else if ( component instanceof JTextField){

                JTextField manaTextField = (JTextField)component;
                String num = Integer.toString(ability.getManaCost());

                manaTextField.setText( num  );
            }
        }
        
    }
    
    public static void main(String[] args){
        
        JFrame frame = new JFrame();
        frame.setSize(2500,2500);
        frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
        frame.setLayout( new BorderLayout() );
        frame.add( new AbilitiesViewport() , BorderLayout.CENTER );
        frame.setVisible(true);
       
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abilitySubPanel5 = new javax.swing.JPanel();
        abilityName5 = new javax.swing.JLabel();
        abilityDecalButton5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        abilitySubPanel7 = new javax.swing.JPanel();
        abilityName7 = new javax.swing.JLabel();
        abilityDecalButton7 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        abilitySubPanel8 = new javax.swing.JPanel();
        abilityName8 = new javax.swing.JLabel();
        abilityDecalButton8 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        abilitySubPanel11 = new javax.swing.JPanel();
        abilityName11 = new javax.swing.JLabel();
        abilityDecalButton11 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        abilitySubPanel12 = new javax.swing.JPanel();
        abilityName12 = new javax.swing.JLabel();
        abilityDecalButton12 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        abilitySubPanel3 = new javax.swing.JPanel();
        abilityName1 = new javax.swing.JLabel();
        abilityDecalButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        abilitySubPanel17 = new javax.swing.JPanel();
        abilityName2 = new javax.swing.JLabel();
        abilityDecalButton17 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        abilitySubPanel19 = new javax.swing.JPanel();
        abilityName4 = new javax.swing.JLabel();
        abilityDecalButton19 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        abilitySubPanel20 = new javax.swing.JPanel();
        abilityName20 = new javax.swing.JLabel();
        abilityDecalButton20 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        abilitySubPanel18 = new javax.swing.JPanel();
        abilityName3 = new javax.swing.JLabel();
        abilityDecalButton18 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();

        abilitySubPanel5.setBackground(new java.awt.Color(101, 79, 57));

        abilityName5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        abilityName5.setForeground(new java.awt.Color(186, 163, 132));
        abilityName5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abilityName5.setText("Abilitie Name");
        abilityName5.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 1, 1, new java.awt.Color(0, 0, 0)));

        abilityDecalButton5.setBackground(new java.awt.Color(101, 79, 57));
        abilityDecalButton5.setText("Decal");
        abilityDecalButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(197, 41, 41), null, null));

        jTextField5.setBackground(new java.awt.Color(101, 79, 57));
        jTextField5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(186, 163, 132));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 4, new java.awt.Color(0, 0, 0)));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abilitySubPanel5Layout = new javax.swing.GroupLayout(abilitySubPanel5);
        abilitySubPanel5.setLayout(abilitySubPanel5Layout);
        abilitySubPanel5Layout.setHorizontalGroup(
            abilitySubPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abilitySubPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abilityName5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abilityDecalButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jTextField5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abilitySubPanel5Layout.setVerticalGroup(
            abilitySubPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abilityName5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abilityDecalButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        abilitySubPanel7.setBackground(new java.awt.Color(101, 79, 57));

        abilityName7.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        abilityName7.setForeground(new java.awt.Color(186, 163, 132));
        abilityName7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abilityName7.setText("Abilitie Name");
        abilityName7.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 1, 1, new java.awt.Color(0, 0, 0)));

        abilityDecalButton7.setBackground(new java.awt.Color(101, 79, 57));
        abilityDecalButton7.setText("Decal");
        abilityDecalButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(197, 41, 41), null, null));

        jTextField7.setBackground(new java.awt.Color(101, 79, 57));
        jTextField7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(186, 163, 132));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 4, new java.awt.Color(0, 0, 0)));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        abilitySubPanel8.setBackground(new java.awt.Color(101, 79, 57));

        abilityName8.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        abilityName8.setForeground(new java.awt.Color(186, 163, 132));
        abilityName8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abilityName8.setText("Abilitie Name");
        abilityName8.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 1, 1, new java.awt.Color(0, 0, 0)));

        abilityDecalButton8.setBackground(new java.awt.Color(101, 79, 57));
        abilityDecalButton8.setText("Decal");
        abilityDecalButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(197, 41, 41), null, null));

        jTextField8.setBackground(new java.awt.Color(101, 79, 57));
        jTextField8.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(186, 163, 132));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("0");
        jTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 4, new java.awt.Color(0, 0, 0)));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abilitySubPanel8Layout = new javax.swing.GroupLayout(abilitySubPanel8);
        abilitySubPanel8.setLayout(abilitySubPanel8Layout);
        abilitySubPanel8Layout.setHorizontalGroup(
            abilitySubPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abilitySubPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abilityName8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abilityDecalButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jTextField8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abilitySubPanel8Layout.setVerticalGroup(
            abilitySubPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abilityName8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abilityDecalButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout abilitySubPanel7Layout = new javax.swing.GroupLayout(abilitySubPanel7);
        abilitySubPanel7.setLayout(abilitySubPanel7Layout);
        abilitySubPanel7Layout.setHorizontalGroup(
            abilitySubPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abilitySubPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abilityName7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abilityDecalButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jTextField7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(abilitySubPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(abilitySubPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(abilitySubPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        abilitySubPanel7Layout.setVerticalGroup(
            abilitySubPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abilityName7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abilityDecalButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(abilitySubPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(abilitySubPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(abilitySubPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        abilitySubPanel11.setBackground(new java.awt.Color(101, 79, 57));

        abilityName11.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        abilityName11.setForeground(new java.awt.Color(186, 163, 132));
        abilityName11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abilityName11.setText("Abilitie Name");
        abilityName11.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 1, 1, new java.awt.Color(0, 0, 0)));

        abilityDecalButton11.setBackground(new java.awt.Color(101, 79, 57));
        abilityDecalButton11.setText("Decal");
        abilityDecalButton11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(197, 41, 41), null, null));

        jTextField11.setBackground(new java.awt.Color(101, 79, 57));
        jTextField11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(186, 163, 132));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("0");
        jTextField11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 4, new java.awt.Color(0, 0, 0)));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abilitySubPanel11Layout = new javax.swing.GroupLayout(abilitySubPanel11);
        abilitySubPanel11.setLayout(abilitySubPanel11Layout);
        abilitySubPanel11Layout.setHorizontalGroup(
            abilitySubPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abilitySubPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abilityName11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abilityDecalButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jTextField11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abilitySubPanel11Layout.setVerticalGroup(
            abilitySubPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abilityName11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abilityDecalButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        abilitySubPanel12.setBackground(new java.awt.Color(101, 79, 57));

        abilityName12.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        abilityName12.setForeground(new java.awt.Color(186, 163, 132));
        abilityName12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abilityName12.setText("Abilitie Name");
        abilityName12.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 1, 1, new java.awt.Color(0, 0, 0)));

        abilityDecalButton12.setBackground(new java.awt.Color(101, 79, 57));
        abilityDecalButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(197, 41, 41), null, null));

        jTextField12.setBackground(new java.awt.Color(101, 79, 57));
        jTextField12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(186, 163, 132));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("0");
        jTextField12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 4, new java.awt.Color(0, 0, 0)));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abilitySubPanel12Layout = new javax.swing.GroupLayout(abilitySubPanel12);
        abilitySubPanel12.setLayout(abilitySubPanel12Layout);
        abilitySubPanel12Layout.setHorizontalGroup(
            abilitySubPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abilitySubPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abilityName12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abilityDecalButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jTextField12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abilitySubPanel12Layout.setVerticalGroup(
            abilitySubPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abilityName12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abilityDecalButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(60, 52, 41));
        setPreferredSize(new java.awt.Dimension(850, 175));

        abilitySubPanel3.setBackground(new java.awt.Color(101, 79, 57));
        abilitySubPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(197, 41, 41)));

        abilityName1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        abilityName1.setForeground(new java.awt.Color(186, 163, 132));
        abilityName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abilityName1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 1, 1, new java.awt.Color(0, 0, 0)));

        abilityDecalButton3.setBackground(new java.awt.Color(101, 79, 57));
        abilityDecalButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(197, 41, 41), null, null));

        jTextField1.setBackground(new java.awt.Color(101, 79, 57));
        jTextField1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(186, 163, 132));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 4, new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abilitySubPanel3Layout = new javax.swing.GroupLayout(abilitySubPanel3);
        abilitySubPanel3.setLayout(abilitySubPanel3Layout);
        abilitySubPanel3Layout.setHorizontalGroup(
            abilitySubPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abilitySubPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abilityName1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abilityDecalButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abilitySubPanel3Layout.setVerticalGroup(
            abilitySubPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abilityName1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abilityDecalButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        abilitySubPanel17.setBackground(new java.awt.Color(101, 79, 57));
        abilitySubPanel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(197, 41, 41)));

        abilityName2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        abilityName2.setForeground(new java.awt.Color(186, 163, 132));
        abilityName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abilityName2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 1, 1, new java.awt.Color(0, 0, 0)));

        abilityDecalButton17.setBackground(new java.awt.Color(101, 79, 57));
        abilityDecalButton17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(197, 41, 41), null, null));

        jTextField2.setBackground(new java.awt.Color(101, 79, 57));
        jTextField2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(186, 163, 132));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 4, new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abilitySubPanel17Layout = new javax.swing.GroupLayout(abilitySubPanel17);
        abilitySubPanel17.setLayout(abilitySubPanel17Layout);
        abilitySubPanel17Layout.setHorizontalGroup(
            abilitySubPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abilitySubPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abilityName2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abilityDecalButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abilitySubPanel17Layout.setVerticalGroup(
            abilitySubPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abilityName2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abilityDecalButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        abilitySubPanel19.setBackground(new java.awt.Color(101, 79, 57));
        abilitySubPanel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(197, 41, 41)));

        abilityName4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        abilityName4.setForeground(new java.awt.Color(186, 163, 132));
        abilityName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abilityName4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 1, 1, new java.awt.Color(0, 0, 0)));

        abilityDecalButton19.setBackground(new java.awt.Color(101, 79, 57));
        abilityDecalButton19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(197, 41, 41), null, null));

        jTextField4.setBackground(new java.awt.Color(101, 79, 57));
        jTextField4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(186, 163, 132));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 4, new java.awt.Color(0, 0, 0)));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abilitySubPanel19Layout = new javax.swing.GroupLayout(abilitySubPanel19);
        abilitySubPanel19.setLayout(abilitySubPanel19Layout);
        abilitySubPanel19Layout.setHorizontalGroup(
            abilitySubPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abilitySubPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abilityName4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abilityDecalButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abilitySubPanel19Layout.setVerticalGroup(
            abilitySubPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abilityName4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abilityDecalButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        abilitySubPanel20.setBackground(new java.awt.Color(101, 79, 57));
        abilitySubPanel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(197, 41, 41)));

        abilityName20.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        abilityName20.setForeground(new java.awt.Color(186, 163, 132));
        abilityName20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abilityName20.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 1, 1, new java.awt.Color(0, 0, 0)));

        abilityDecalButton20.setBackground(new java.awt.Color(101, 79, 57));
        abilityDecalButton20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(197, 41, 41), null, null));

        jTextField6.setBackground(new java.awt.Color(101, 79, 57));
        jTextField6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(186, 163, 132));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 4, new java.awt.Color(0, 0, 0)));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abilitySubPanel20Layout = new javax.swing.GroupLayout(abilitySubPanel20);
        abilitySubPanel20.setLayout(abilitySubPanel20Layout);
        abilitySubPanel20Layout.setHorizontalGroup(
            abilitySubPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abilitySubPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abilityName20, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abilityDecalButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abilitySubPanel20Layout.setVerticalGroup(
            abilitySubPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abilityName20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abilityDecalButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        abilitySubPanel18.setBackground(new java.awt.Color(101, 79, 57));
        abilitySubPanel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(197, 41, 41)));

        abilityName3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        abilityName3.setForeground(new java.awt.Color(186, 163, 132));
        abilityName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abilityName3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 1, 1, new java.awt.Color(0, 0, 0)));

        abilityDecalButton18.setBackground(new java.awt.Color(101, 79, 57));
        abilityDecalButton18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(197, 41, 41), null, null));

        jTextField3.setBackground(new java.awt.Color(101, 79, 57));
        jTextField3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(186, 163, 132));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 4, 4, new java.awt.Color(0, 0, 0)));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abilitySubPanel18Layout = new javax.swing.GroupLayout(abilitySubPanel18);
        abilitySubPanel18.setLayout(abilitySubPanel18Layout);
        abilitySubPanel18Layout.setHorizontalGroup(
            abilitySubPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abilitySubPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abilityName3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abilityDecalButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abilitySubPanel18Layout.setVerticalGroup(
            abilitySubPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abilitySubPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abilityName3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abilityDecalButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abilitySubPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(abilitySubPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(abilitySubPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(abilitySubPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(abilitySubPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abilitySubPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abilitySubPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abilitySubPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abilitySubPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abilitySubPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abilityDecalButton11;
    private javax.swing.JButton abilityDecalButton12;
    private javax.swing.JButton abilityDecalButton17;
    private javax.swing.JButton abilityDecalButton18;
    private javax.swing.JButton abilityDecalButton19;
    private javax.swing.JButton abilityDecalButton20;
    private javax.swing.JButton abilityDecalButton3;
    private javax.swing.JButton abilityDecalButton5;
    private javax.swing.JButton abilityDecalButton7;
    private javax.swing.JButton abilityDecalButton8;
    private javax.swing.JLabel abilityName1;
    private javax.swing.JLabel abilityName11;
    private javax.swing.JLabel abilityName12;
    private javax.swing.JLabel abilityName2;
    private javax.swing.JLabel abilityName20;
    private javax.swing.JLabel abilityName3;
    private javax.swing.JLabel abilityName4;
    private javax.swing.JLabel abilityName5;
    private javax.swing.JLabel abilityName7;
    private javax.swing.JLabel abilityName8;
    private javax.swing.JPanel abilitySubPanel11;
    private javax.swing.JPanel abilitySubPanel12;
    private javax.swing.JPanel abilitySubPanel17;
    private javax.swing.JPanel abilitySubPanel18;
    private javax.swing.JPanel abilitySubPanel19;
    private javax.swing.JPanel abilitySubPanel20;
    private javax.swing.JPanel abilitySubPanel3;
    private javax.swing.JPanel abilitySubPanel5;
    private javax.swing.JPanel abilitySubPanel7;
    private javax.swing.JPanel abilitySubPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
