/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.viewport;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import model.GameObject;
import utility.IntentComponentMap;

/**
 *
 * @author comcc_000
 */
public class DialogueViewport extends ViewPort {
    
    /**
     * Creates new form DialogueViewport
     */
    public DialogueViewport() {
		initComponents();
		setBackground(Color.BLACK);
		//components should be text and button in panel
		
	}

	private void initInteriorViewports() {
		//interiorViewports.add(new FlavorImageViewport());
	}

	private void addInteriorViewports() {
		int numInteriorViewports = interiorViewports.size();
		ViewPort view;
		JPanel panel;
		for (int i = 0; i < numInteriorViewports; i++) {
			view = interiorViewports.get(i);
//			panel = (JPanel) view;
//			add(panel);

		}
	}

	@Override
	public void updateView(GameObject gameObject) {

	}

	@Override
	public ArrayList<IntentComponentMap> generateIntentComponentMapping() {
		// subviewports have all the components...
		ArrayList<IntentComponentMap> icms = new ArrayList<IntentComponentMap>(
				1);
//		icms.add(new IntentComponentMap(continuePastDialogueButton,
//				IntentComponentMap.Intent.GOTO_GAME));
		return icms;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
