/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.viewport;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import model.GameObject;
import model.Model;


/**
 *
 * @author Carlos Vizcaino
 */
public class GameScreenViewport extends ViewPort {
    
    public static void main(String[] args){
        
        JFrame frame = new JFrame();
        frame.setSize(2500,2500);
        frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
        frame.add( new GameScreenViewport() );
        
        System.out.println("This is running...");
        frame.setVisible(true);
    }
    
    // Default Constructor
    public GameScreenViewport() {
        
        initComponents();
        generateView();
        
         
    }
    
    // Constructor I
    public GameScreenViewport(Model model){
        initComponents();
        generateView();
        
    }
   
    
    public void generateView(){
        
        //Create the viewports to be included in the screen
        AreaViewport areaViewport = new AreaViewport();
        InventoryViewPort inventoryViewport = new InventoryViewPort();
        StatusViewport statusViewport = new StatusViewport();
        AbilitiesViewport abilitiesViewport = new AbilitiesViewport();
        DialogueViewport dialogueViewport = new DialogueViewport();
        
        //Add viewports to their places
        this.addViewport(areaViewport);
        GamePanel.setLayout( new BorderLayout() );
        GamePanel.add( areaViewport , BorderLayout.CENTER );
            //
        this.addViewport(statusViewport);
        StatisticsPanel.setLayout( new BorderLayout() );
        StatisticsPanel.add( statusViewport, BorderLayout.CENTER);
        StatisticsPanel.revalidate();
        StatisticsPanel.repaint();
            //
        this.addViewport( inventoryViewport );
        InventoryMainPanel.setLayout( new BorderLayout() );
        InventoryMainPanel.add( inventoryViewport , BorderLayout.CENTER );
            //
        this.addViewport( abilitiesViewport );
        AbilitiesPanel.setLayout( new BorderLayout() );
        AbilitiesPanel.add( abilitiesViewport , BorderLayout.CENTER );
            //
        this.addViewport( abilitiesViewport );
        AbilitiesPanel.setLayout( new BorderLayout() );
        AbilitiesPanel.add( abilitiesViewport , BorderLayout.CENTER );
        
        this.addViewport( dialogueViewport );
        DialoguePanel.setLayout( new BorderLayout() );
        DialoguePanel.add( dialogueViewport , BorderLayout.CENTER );
        
        //Update
        this.revalidate();
        this.repaint();
    }
    
    @Override
    public void updateView(GameObject gameObject) {
        
        int numInteriorViewports = interiorViewports.size();
        ViewPort viewport;
        for (int i=0; i<numInteriorViewports; i++) {
            viewport = interiorViewports.get(i);
            viewport.updateView(gameObject);
        }
    }
    
    /*
     @Override
    protected void paintComponent(Graphics g){
        
        super.paintComponent(g);
        ImageIcon image = new ImageIcon( new Decal("./Sprites/backgrounds/rockPirateBig.jpg").getImage());
        g.drawImage( image.getImage() , 0, 0, this.getWidth(), this.getHeight(), this);
    }
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GamePanel = new javax.swing.JPanel();
        DialoguePanel = new javax.swing.JPanel();
        StatisticsPanel = new javax.swing.JPanel();
        InventoryMainPanel = new javax.swing.JPanel();
        AbilitiesPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(1, 13, 25));
        setPreferredSize(new java.awt.Dimension(470, 342));

        GamePanel.setBackground(new java.awt.Color(152, 107, 61));

        javax.swing.GroupLayout GamePanelLayout = new javax.swing.GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        GamePanelLayout.setVerticalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        DialoguePanel.setBackground(new java.awt.Color(224, 23, 47));

        javax.swing.GroupLayout DialoguePanelLayout = new javax.swing.GroupLayout(DialoguePanel);
        DialoguePanel.setLayout(DialoguePanelLayout);
        DialoguePanelLayout.setHorizontalGroup(
            DialoguePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        DialoguePanelLayout.setVerticalGroup(
            DialoguePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout StatisticsPanelLayout = new javax.swing.GroupLayout(StatisticsPanel);
        StatisticsPanel.setLayout(StatisticsPanelLayout);
        StatisticsPanelLayout.setHorizontalGroup(
            StatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        StatisticsPanelLayout.setVerticalGroup(
            StatisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        InventoryMainPanel.setBackground(new java.awt.Color(48, 226, 27));

        javax.swing.GroupLayout InventoryMainPanelLayout = new javax.swing.GroupLayout(InventoryMainPanel);
        InventoryMainPanel.setLayout(InventoryMainPanelLayout);
        InventoryMainPanelLayout.setHorizontalGroup(
            InventoryMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        InventoryMainPanelLayout.setVerticalGroup(
            InventoryMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        AbilitiesPanel.setBackground(new java.awt.Color(179, 33, 220));

        javax.swing.GroupLayout AbilitiesPanelLayout = new javax.swing.GroupLayout(AbilitiesPanel);
        AbilitiesPanel.setLayout(AbilitiesPanelLayout);
        AbilitiesPanelLayout.setHorizontalGroup(
            AbilitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        AbilitiesPanelLayout.setVerticalGroup(
            AbilitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DialoguePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AbilitiesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StatisticsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InventoryMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StatisticsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InventoryMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DialoguePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AbilitiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbilitiesPanel;
    private javax.swing.JPanel DialoguePanel;
    private javax.swing.JPanel GamePanel;
    private javax.swing.JPanel InventoryMainPanel;
    private javax.swing.JPanel StatisticsPanel;
    // End of variables declaration//GEN-END:variables
}
