/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.viewport;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import model.GameObject;
import model.Model;
import utility.IntentComponentMap;
import utility.IntentComponentMap.Intent;

/**
 *
 * @author darien
 */
public class LoadSavePopUpViewport extends ViewPort {

    /**
     * Creates new form LoadSavePopUpViewport
     */
    Model model;
    private ArrayList<IntentComponentMap> icms = new ArrayList<IntentComponentMap>(1);
    
    public LoadSavePopUpViewport() {
        initComponents();
        createTreePanelGUI();
    }
    
    public LoadSavePopUpViewport(Model model){
    
           this.model = model;
           initComponents();
           createTreePanelGUI();   
    }
    
    @Override
    public void updateView(GameObject gameObject) {
    
        //createTreePanelGUI();
    }
    
    @Override
    public ArrayList<IntentComponentMap> generateIntentComponentMapping() {
        
        System.out.println("Intent Componenet is being called");
        icms.add ( new IntentComponentMap(loadButton, Intent.LOAD) );
        icms.add ( new IntentComponentMap(userInstructionLabel, Intent.LABEL));
        icms.add ( new IntentComponentMap(playerRecordsTreePanel, Intent.TREE_PANEL));
        icms.add ( new IntentComponentMap(continueAdventureButton, Intent.GOTO_GAME));
        icms.add ( new IntentComponentMap(backButton, Intent.GOTO_MAIN));
       
        return icms;
    }

    
    private void createTreePanelGUI(){
        
        // This is the root of the tree
        DefaultMutableTreeNode top = new DefaultMutableTreeNode("Avatars");
        
        File folder = new File("LoadSave/");
        File[] listOfFiles = folder.listFiles();

        for (File file : listOfFiles) {
            
            if (file.isDirectory()) {
               
                // Create Directory Node
                DefaultMutableTreeNode directoryName = new DefaultMutableTreeNode(file.getName());
                top.add(directoryName);

                File avatarFiles = new File( "LoadSave/" + file.getName() + "/" );
                File [] listOfAvatarFiles = avatarFiles.listFiles();
                System.out.println( listOfAvatarFiles.length );
                
                if ( avatarFiles != null && avatarFiles.exists()){
                
                    for ( File i : listOfAvatarFiles){

                        if (i.isFile() ){

                            // Create File Nodes
                            System.out.println( i.getName() );
                            DefaultMutableTreeNode fileName = new DefaultMutableTreeNode(i.getName());
                            directoryName.add(fileName);
                        } 
                    }
                
                }
            }
        }
       playerRecordsTreePanel = new JTree( top );
       playerRecordsTreePanel.setBackground( new Color (123,38,38));
       playerRecordsTreePanel.setModel(new javax.swing.tree.DefaultTreeModel(top));
       jScrollPane3.setViewportView(playerRecordsTreePanel);
      
    }
 
    /*
    private void makeGUI()
{
   DefaultMutableTreeNode top=new DefaultMutableTreeNode("Language");
   DefaultMutableTreeNode a=new DefaultMutableTreeNode("Programming");
   top.add(a);
   DefaultMutableTreeNode a1=new DefaultMutableTreeNode("C");
   a.add(a1);
   DefaultMutableTreeNode a2=new DefaultMutableTreeNode("Java");
   a.add(a2);
   DefaultMutableTreeNode b=new DefaultMutableTreeNode("Web Based");
   top.add(b);
   DefaultMutableTreeNode b1=new DefaultMutableTreeNode("PHP");
   b.add(b1);
   DefaultMutableTreeNode b2=new DefaultMutableTreeNode("JSP");
   b.add(b2);
   t=new JTree(top);
   JScrollPane scr=new JScrollPane(t);
   add(scr);
   setLayout(new  FlowLayout());
   l1=new JLabel("Choose a language");
   add(l1,BorderLayout.SOUTH);
   t.addTreeSelectionListener(new TreeSelectionListener () {
    public void valueChanged(TreeSelectionEvent ae) { 
      l1.setText(ae.getPath()+" is selected");
    }
  });
   
 }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadSavePanel = new javax.swing.JPanel();
        loadSaveFunctionalitiesPanel = new javax.swing.JPanel();
        loadButton = new javax.swing.JButton();
        continueAdventureButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        columnNamesPanel = new javax.swing.JPanel();
        userInstructionLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        playerRecordsTreePanel = new javax.swing.JTree();

        setBackground(new java.awt.Color(148, 61, 78));
        setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(1120, 834));
        setMinimumSize(new java.awt.Dimension(1120, 834));

        loadSavePanel.setBackground(new java.awt.Color(70, 52, 35));
        loadSavePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));

        loadSaveFunctionalitiesPanel.setBackground(new java.awt.Color(218, 142, 66));

        loadButton.setText("Load");

        continueAdventureButton.setText("Continue Adventure");

        backButton.setText("Back");

        javax.swing.GroupLayout loadSaveFunctionalitiesPanelLayout = new javax.swing.GroupLayout(loadSaveFunctionalitiesPanel);
        loadSaveFunctionalitiesPanel.setLayout(loadSaveFunctionalitiesPanelLayout);
        loadSaveFunctionalitiesPanelLayout.setHorizontalGroup(
            loadSaveFunctionalitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadSaveFunctionalitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(continueAdventureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        loadSaveFunctionalitiesPanelLayout.setVerticalGroup(
            loadSaveFunctionalitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadSaveFunctionalitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loadSaveFunctionalitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton)
                    .addComponent(continueAdventureButton)
                    .addComponent(backButton))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        columnNamesPanel.setBackground(new java.awt.Color(226, 177, 127));

        userInstructionLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        userInstructionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userInstructionLabel.setText("Select desired game by the Avatar's Name, Level and Date/Time");
        userInstructionLabel.setMaximumSize(new java.awt.Dimension(548, 31));
        userInstructionLabel.setMinimumSize(new java.awt.Dimension(548, 31));
        userInstructionLabel.setPreferredSize(new java.awt.Dimension(548, 31));

        javax.swing.GroupLayout columnNamesPanelLayout = new javax.swing.GroupLayout(columnNamesPanel);
        columnNamesPanel.setLayout(columnNamesPanelLayout);
        columnNamesPanelLayout.setHorizontalGroup(
            columnNamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(columnNamesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userInstructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        columnNamesPanelLayout.setVerticalGroup(
            columnNamesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(columnNamesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userInstructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));

        playerRecordsTreePanel.setBackground(new java.awt.Color(123, 38, 38));
        playerRecordsTreePanel.setMinimumSize(new java.awt.Dimension(81, 80));
        playerRecordsTreePanel.setName(""); // NOI18N
        playerRecordsTreePanel.setRowHeight(-20);
        jScrollPane3.setViewportView(playerRecordsTreePanel);

        javax.swing.GroupLayout loadSavePanelLayout = new javax.swing.GroupLayout(loadSavePanel);
        loadSavePanel.setLayout(loadSavePanelLayout);
        loadSavePanelLayout.setHorizontalGroup(
            loadSavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadSaveFunctionalitiesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(columnNamesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(loadSavePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        loadSavePanelLayout.setVerticalGroup(
            loadSavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadSavePanelLayout.createSequentialGroup()
                .addComponent(columnNamesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadSaveFunctionalitiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(loadSavePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loadSavePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 346, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel columnNamesPanel;
    private javax.swing.JButton continueAdventureButton;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton loadButton;
    private javax.swing.JPanel loadSaveFunctionalitiesPanel;
    private javax.swing.JPanel loadSavePanel;
    private javax.swing.JTree playerRecordsTreePanel;
    private javax.swing.JLabel userInstructionLabel;
    // End of variables declaration//GEN-END:variables
}
