/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.viewport;

import javax.swing.JPanel;
import view.screen.Screen;

/**
 *
 * @author comcc_000
 */
public class MainWindow extends javax.swing.JFrame {

    /*Properties*/
    
    private Screen screen;
    
    /*Constructor*/
    
    public MainWindow() {
        initComponents();
    }
    
    public void displayScreen(Screen screen) {
        this.screen = screen;
        ViewPort view = screen.getViewPort();
        
        setSize(view);
        this.getContentPane().removeAll();
        addViewport(view);
        //addInteriorViewports(view);
        
        pack();
        setVisible(true);
    }
    
    public void addViewport(ViewPort view) {
        this.getContentPane().add(view);
        view.updateUI();
    }
    
//    public void addInteriorViewports(ViewPort view) {
//        ArrayList<ViewPort> interiorViewports = view.getInteriorViewports();
//        if (interiorViewports != null) {
//            int numInteriorViewports = interiorViewports.size();
//            ViewPort interiorViewport;
//            for (int i=0; i<numInteriorViewports; i++) {
//                interiorViewport = interiorViewports.get(i);
//                addViewport(interiorViewport);
//            }
//        }
//    }
    
    public void setSize(ViewPort view) {
        JPanel panel = view;
        int width = this.getWidth();
        int height = this.getHeight();
        panel.setBounds(0, 0, width, height); //x,y top right coordinate, then width, height
    }
    
    /*Methods*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
			public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
