/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.viewport;

import java.awt.Dimension;
import java.util.ArrayList;

import model.GameObject;
import model.entity.Statistics;
import utility.IntentComponentMap;

/**
 *
 * @author comcc_000
 */
public class StatusViewport extends ViewPort {

    /**
     * Creates new form StatusViewport
     */
    public StatusViewport() {
        initComponents();
    }
    
    @Override
    public void updateView(GameObject gameObject) {
        Statistics statistics = gameObject.getAvatar().getDerivedStatistics();
    
        int health = statistics.getCurrentHealth();
        int mana = statistics.getCurrentMana();
        int level = statistics.getLevel();
        int livesLeft = statistics.getLivesLeft(); 
        int offense = statistics.getOffensiveRating();
        int defense = statistics.getDefensiveRating();
        int armor = statistics.getArmorRating();
        int strength = statistics.getStrength();
        int agility = statistics.getAgility();
        int intellect = statistics.getIntellect();
        int hardiness = statistics.getHardiness();
        int experience = statistics.getExperience();
        int movement = statistics.getMovement();

        Dimension textFieldDim = new Dimension(50, 28);
        healthField.setText(Integer.toString(health));
        manaField.setText(Integer.toString(mana));
        levelField.setText(Integer.toString(level));
        livesField.setText(Integer.toString(livesLeft));
        offensiveRatingField.setText(Integer.toString(offense));
        defensiveRatingField.setText(Integer.toString(defense));
        armorRatingField.setText(Integer.toString(armor));
        strengthField.setText(Integer.toString(strength));
        agilityField.setText(Integer.toString(agility));
        intellectField.setText(Integer.toString(intellect));
        hardinessField.setText(Integer.toString(hardiness));
        experienceField.setText(Integer.toString(experience));
        movementField.setText(Integer.toString(movement));
        
        healthField.setMinimumSize(textFieldDim);
        manaField.setMinimumSize(textFieldDim);
        levelField.setMinimumSize(textFieldDim);
        livesField.setMinimumSize(textFieldDim);
        offensiveRatingField.setMinimumSize(textFieldDim);
        defensiveRatingField.setMinimumSize(textFieldDim);
        armorRatingField.setMinimumSize(textFieldDim);
        strengthField.setMinimumSize(textFieldDim);
        agilityField.setMinimumSize(textFieldDim);
        intellectField.setMinimumSize(textFieldDim);
        hardinessField.setMinimumSize(textFieldDim);
        experienceField.setMinimumSize(textFieldDim);
        movementField.setMinimumSize(textFieldDim);
    }

    @Override
    public ArrayList<IntentComponentMap> generateIntentComponentMapping() {
        ArrayList<IntentComponentMap> icms = new ArrayList<IntentComponentMap>(1);
        return icms;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        healthField = new javax.swing.JTextField();
        manaField = new javax.swing.JTextField();
        healthLabel = new javax.swing.JLabel();
        manaLabel = new javax.swing.JLabel();
        livesLabel = new javax.swing.JLabel();
        offensiveRatingLabel = new javax.swing.JLabel();
        defensiveRatingLabel = new javax.swing.JLabel();
        armorRatingLabel = new javax.swing.JLabel();
        strengthLabel = new javax.swing.JLabel();
        agilityLabel = new javax.swing.JLabel();
        intellectLabel = new javax.swing.JLabel();
        hardinessLabel = new javax.swing.JLabel();
        experienceLabel = new javax.swing.JLabel();
        movementLabel = new javax.swing.JLabel();
        livesField = new javax.swing.JTextField();
        offensiveRatingField = new javax.swing.JTextField();
        defensiveRatingField = new javax.swing.JTextField();
        armorRatingField = new javax.swing.JTextField();
        strengthField = new javax.swing.JTextField();
        agilityField = new javax.swing.JTextField();
        intellectField = new javax.swing.JTextField();
        hardinessField = new javax.swing.JTextField();
        experienceField = new javax.swing.JTextField();
        movementField = new javax.swing.JTextField();
        levelLabel = new javax.swing.JLabel();
        levelField = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(250, 250));
        setLayout(new java.awt.GridBagLayout());

        healthField.setEditable(false);
        healthField.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(healthField, gridBagConstraints);

        manaField.setEditable(false);
        manaField.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(manaField, gridBagConstraints);

        healthLabel.setText("Health");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(healthLabel, gridBagConstraints);

        manaLabel.setText("Mana");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(manaLabel, gridBagConstraints);

        livesLabel.setText("Lives Left");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(livesLabel, gridBagConstraints);

        offensiveRatingLabel.setText("Offensive Rating");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(offensiveRatingLabel, gridBagConstraints);

        defensiveRatingLabel.setText("Defensive Rating");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        add(defensiveRatingLabel, gridBagConstraints);

        armorRatingLabel.setText("Armor Rating");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        add(armorRatingLabel, gridBagConstraints);

        strengthLabel.setText("Strength");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        add(strengthLabel, gridBagConstraints);

        agilityLabel.setText("Agility");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        add(agilityLabel, gridBagConstraints);

        intellectLabel.setText("Intellect");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        add(intellectLabel, gridBagConstraints);

        hardinessLabel.setText("Hardiness");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        add(hardinessLabel, gridBagConstraints);

        experienceLabel.setText("Experience");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        add(experienceLabel, gridBagConstraints);

        movementLabel.setText("Movement");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        add(movementLabel, gridBagConstraints);

        livesField.setEditable(false);
        livesField.setText("jTextField3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(livesField, gridBagConstraints);

        offensiveRatingField.setEditable(false);
        offensiveRatingField.setText("jTextField4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        add(offensiveRatingField, gridBagConstraints);

        defensiveRatingField.setEditable(false);
        defensiveRatingField.setText("jTextField5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        add(defensiveRatingField, gridBagConstraints);

        armorRatingField.setEditable(false);
        armorRatingField.setText("jTextField6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        add(armorRatingField, gridBagConstraints);

        strengthField.setEditable(false);
        strengthField.setText("jTextField7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        add(strengthField, gridBagConstraints);

        agilityField.setEditable(false);
        agilityField.setText("Sample Text");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        add(agilityField, gridBagConstraints);

        intellectField.setEditable(false);
        intellectField.setText("jTextField9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        add(intellectField, gridBagConstraints);

        hardinessField.setEditable(false);
        hardinessField.setText("jTextField10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        add(hardinessField, gridBagConstraints);

        experienceField.setEditable(false);
        experienceField.setText("jTextField11");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        add(experienceField, gridBagConstraints);

        movementField.setEditable(false);
        movementField.setText("jTextField12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        add(movementField, gridBagConstraints);

        levelLabel.setText("Level");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(levelLabel, gridBagConstraints);

        levelField.setEditable(false);
        levelField.setText("jTextField1");
        levelField.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(levelField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void levelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agilityField;
    private javax.swing.JLabel agilityLabel;
    private javax.swing.JTextField armorRatingField;
    private javax.swing.JLabel armorRatingLabel;
    private javax.swing.JTextField defensiveRatingField;
    private javax.swing.JLabel defensiveRatingLabel;
    private javax.swing.JTextField experienceField;
    private javax.swing.JLabel experienceLabel;
    private javax.swing.JTextField hardinessField;
    private javax.swing.JLabel hardinessLabel;
    private javax.swing.JTextField healthField;
    private javax.swing.JLabel healthLabel;
    private javax.swing.JTextField intellectField;
    private javax.swing.JLabel intellectLabel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JTextField levelField;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField livesField;
    private javax.swing.JLabel livesLabel;
    private javax.swing.JTextField manaField;
    private javax.swing.JLabel manaLabel;
    private javax.swing.JTextField movementField;
    private javax.swing.JLabel movementLabel;
    private javax.swing.JTextField offensiveRatingField;
    private javax.swing.JLabel offensiveRatingLabel;
    private javax.swing.JTextField strengthField;
    private javax.swing.JLabel strengthLabel;
    // End of variables declaration//GEN-END:variables
}
