/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.viewport;

import java.awt.BorderLayout;
import java.awt.Component;
import model.GameObject;

/**
 *
 * @author comcc_000
 */
public class TradeScreenViewport extends ViewPort {

    /*Properites*/

    public TradeScreenViewport() {
        initComponents();
        generateView();
    }
    
    public void generateView() {  
        FlavorImageViewport flavorImageViewport = new FlavorImageViewport();
        TradeViewport tradeViewport = new TradeViewport();
        
        this.addViewport(flavorImageViewport);
        FlavorImagePanel.setLayout( new BorderLayout() );
        FlavorImagePanel.add( flavorImageViewport , BorderLayout.CENTER );
        
        this.addViewport(tradeViewport);
        TradePanel.setLayout( new BorderLayout() );
        TradePanel.add( tradeViewport , BorderLayout.CENTER );
        
        this.revalidate();
        this.repaint();
    }

    @Override
    public void updateView(GameObject gameObject) {
        int numInteriorViewports = interiorViewports.size();
        ViewPort viewport;
        for (int i=0; i < numInteriorViewports; i++) {
            viewport = interiorViewports.get(i);
            viewport.updateView(gameObject);
        }
    }

    /* Inner classes */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FlavorImagePanel = new javax.swing.JPanel();
        TradePanel = new javax.swing.JPanel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        javax.swing.GroupLayout FlavorImagePanelLayout = new javax.swing.GroupLayout(FlavorImagePanel);
        FlavorImagePanel.setLayout(FlavorImagePanelLayout);
        FlavorImagePanelLayout.setHorizontalGroup(
            FlavorImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        FlavorImagePanelLayout.setVerticalGroup(
            FlavorImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TradePanelLayout = new javax.swing.GroupLayout(TradePanel);
        TradePanel.setLayout(TradePanelLayout);
        TradePanelLayout.setHorizontalGroup(
            TradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        TradePanelLayout.setVerticalGroup(
            TradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FlavorImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TradePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FlavorImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TradePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        
    }//GEN-LAST:event_formComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FlavorImagePanel;
    private javax.swing.JPanel TradePanel;
    // End of variables declaration//GEN-END:variables
}

